### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by Tylwen** [ASangarin/MythicKeys#8]
Hello,

Can you upgrade the client to fabric 1.19.2?

Regards

**Comment by Tylwen** [comment]
"Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
     - Replace mod 'MythicKeys' (mythickeys) 1.2.2 with any version that is compatible with:
         - minecraft 1.19.2
Unmet dependency listing:
     - Mod 'MythicKeys' (mythickeys) 1.2.2 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
    at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)"

**Comment by ASangarin** [comment]
I'll wait until 1.19.3 comes out, then I'll make an update for both new
versions.

**Comment by ASangarin** [comment]
Released.
